//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademicWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BioStatProject_DAEntities : DbContext
    {
        public BioStatProject_DAEntities()
            : base("name=BioStatProject_DAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetSeminarReport2_Result> GetSeminarReport2(string biostat, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var biostatParameter = biostat != null ?
                new ObjectParameter("Biostat", biostat) :
                new ObjectParameter("Biostat", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSeminarReport2_Result>("GetSeminarReport2", biostatParameter, fromDateParameter, toDateParameter);
        }
    }
}
